import type { Property, Unit } from '@/lib/types/property'

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    type: 'Immeuble',
    name: 'Résidence Les Cocotiers',
    address: {
      street: 'Boulevard de la République',
      city: 'Abidjan',
      postalCode: '01 BP',
      country: 'Côte d\'Ivoire',
    },
    owner: {
      id: 'owner-1',
      name: 'Kouassi Amadou',
      email: 'kouassi.amadou@email.ci',
      phone: '+225 07 12 34 56 78',
    },
    status: 'Occupé',
    totalUnits: 24,
    occupiedUnits: 20,
    units: [
      {
        id: 'unit-1',
        number: '1A',
        floor: 1,
        rooms: 2,
        size: 65,
        rent: 150000,
        status: 'Occupé',
        tenantId: 'tenant-1',
        tenantName: 'Jean Kouamé',
        tenantPhone: '+225 07 11 22 33 44',
        tenantEmail: 'jean.kouame@email.ci',
      },
      {
        id: 'unit-2',
        number: '1B',
        floor: 1,
        rooms: 3,
        size: 85,
        rent: 200000,
        status: 'Occupé',
        tenantId: 'tenant-2',
        tenantName: 'Marie Traoré',
        tenantPhone: '+225 05 22 33 44 55',
        tenantEmail: 'marie.traore@email.ci',
      },
      {
        id: 'unit-3',
        number: '2A',
        floor: 2,
        rooms: 2,
        size: 65,
        rent: 150000,
        status: 'Libre',
      },
      {
        id: 'unit-4',
        number: '2B',
        floor: 2,
        rooms: 3,
        size: 85,
        rent: 200000,
        status: 'Réservé',
      },
      {
        id: 'unit-5',
        number: '2C',
        floor: 2,
        rooms: 2,
        size: 65,
        rent: 150000,
        status: 'Occupé',
        tenantId: 'tenant-3',
        tenantName: 'Pierre Diabaté',
        tenantPhone: '+225 01 33 44 55 66',
        tenantEmail: 'pierre.diabate@email.ci',
      },
      {
        id: 'unit-6',
        number: '2D',
        floor: 2,
        rooms: 3,
        size: 85,
        rent: 200000,
        status: 'Occupé',
        tenantId: 'tenant-4',
        tenantName: 'Sophie Koné',
        tenantPhone: '+225 07 44 55 66 77',
        tenantEmail: 'sophie.kone@email.ci',
      },
      {
        id: 'unit-7',
        number: '3A',
        floor: 3,
        rooms: 2,
        size: 65,
        rent: 150000,
        status: 'Occupé',
        tenantId: 'tenant-5',
        tenantName: 'Paul Soro',
        tenantPhone: '+225 05 55 66 77 88',
        tenantEmail: 'paul.soro@email.ci',
      },
      {
        id: 'unit-8',
        number: '3B',
        floor: 3,
        rooms: 3,
        size: 85,
        rent: 200000,
        status: 'En Maintenance',
      },
      {
        id: 'unit-9',
        number: '3C',
        floor: 3,
        rooms: 2,
        size: 65,
        rent: 150000,
        status: 'Occupé',
        tenantId: 'tenant-6',
        tenantName: 'Lucie Ouattara',
        tenantPhone: '+225 07 66 77 88 99',
        tenantEmail: 'lucie.ouattara@email.ci',
      },
      {
        id: 'unit-10',
        number: '3D',
        floor: 3,
        rooms: 2,
        size: 65,
        rent: 150000,
        status: 'Occupé',
        tenantId: 'tenant-7',
        tenantName: 'Thomas Bamba',
        tenantPhone: '+225 01 77 88 99 00',
        tenantEmail: 'thomas.bamba@email.ci',
      },
      {
        id: 'unit-11',
        number: '4A',
        floor: 4,
        rooms: 2,
        size: 65,
        rent: 150000,
        status: 'Occupé',
        tenantId: 'tenant-8',
        tenantName: 'Emma Sangaré',
        tenantPhone: '+225 05 88 99 00 11',
        tenantEmail: 'emma.sangare@email.ci',
      },
      {
        id: 'unit-12',
        number: '4B',
        floor: 4,
        rooms: 3,
        size: 85,
        rent: 200000,
        status: 'Occupé',
        tenantId: 'tenant-9',
        tenantName: 'Lucas Fofana',
        tenantPhone: '+225 07 99 00 11 22',
        tenantEmail: 'lucas.fofana@email.ci',
      },
    ],
    description: 'Résidence moderne avec vue sur la lagune, située dans un quartier calme et résidentiel de Cocody. Proche des commerces et des transports.',
    createdAt: '2024-01-15',
    updatedAt: '2024-01-20',
    photos: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
  },
  {
    id: 'prop-2',
    type: 'Villa',
    name: 'Villa Lagune',
    address: {
      street: 'Avenue Franchet d\'Esperey',
      city: 'Abidjan',
      postalCode: '08 BP',
      country: 'Côte d\'Ivoire',
    },
    owner: {
      id: 'owner-2',
      name: 'Fatou Diallo',
      email: 'fatou.diallo@email.ci',
      phone: '+225 05 23 45 67 89',
    },
    status: 'Occupé',
    totalUnits: 8,
    occupiedUnits: 7,
    description: 'Villa de luxe avec piscine et jardin, idéale pour les familles. Vue panoramique sur la lagune Ébrié.',
    createdAt: '2024-02-01',
    updatedAt: '2024-02-05',
    photos: ['https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800'],
  },
  {
    id: 'prop-3',
    type: 'Maison',
    name: 'Maison Familiale Marcory',
    address: {
      street: 'Rue des Jardins',
      city: 'Abidjan',
      postalCode: '18 BP',
      country: 'Côte d\'Ivoire',
    },
    owner: {
      id: 'owner-3',
      name: 'Moussa Konaté',
      email: 'moussa.konate@email.ci',
      phone: '+225 01 34 56 78 90',
    },
    status: 'Libre',
    description: 'Maison spacieuse avec jardin, parfaite pour une famille. Quartier résidentiel calme de Marcory.',
    createdAt: '2024-01-10',
    updatedAt: '2024-01-10',
    photos: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800'],
  },
  {
    id: 'prop-4',
    type: 'Commercial',
    name: 'Espace Commercial Plateau',
    address: {
      street: 'Avenue Chardy',
      city: 'Abidjan',
      postalCode: '01 BP',
      country: 'Côte d\'Ivoire',
    },
    owner: {
      id: 'owner-4',
      name: 'Aissatou Cissé',
      email: 'aissatou.cisse@email.ci',
      phone: '+225 07 45 67 89 01',
    },
    status: 'Réservé',
    totalUnits: 15,
    occupiedUnits: 12,
    description: 'Local commercial au cœur du Plateau, idéal pour une boutique ou un bureau. Emplacement stratégique avec forte affluence.',
    createdAt: '2024-01-20',
    updatedAt: '2024-01-25',
    photos: ['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
  },
  {
    id: 'prop-5',
    type: 'Immeuble',
    name: 'Résidence Le Plateau',
    address: {
      street: 'Boulevard de la Paix',
      city: 'Yamoussoukro',
      postalCode: '01 BP',
      country: 'Côte d\'Ivoire',
    },
    owner: {
      id: 'owner-5',
      name: 'Ibrahima Touré',
      email: 'ibrahima.toure@email.ci',
      phone: '+225 05 56 78 90 12',
    },
    status: 'Occupé',
    totalUnits: 32,
    occupiedUnits: 28,
    units: [
      {
        id: 'unit-13',
        number: '1A',
        floor: 1,
        rooms: 2,
        size: 60,
        rent: 120000,
        status: 'Occupé',
        tenantId: 'tenant-10',
        tenantName: 'Camille Kouassi',
        tenantPhone: '+225 05 10 20 30 40',
        tenantEmail: 'camille.kouassi@email.ci',
      },
      {
        id: 'unit-14',
        number: '1B',
        floor: 1,
        rooms: 2,
        size: 60,
        rent: 120000,
        status: 'Libre',
      },
      {
        id: 'unit-15',
        number: '2A',
        floor: 2,
        rooms: 3,
        size: 80,
        rent: 180000,
        status: 'Occupé',
        tenantId: 'tenant-11',
        tenantName: 'Nicolas Bamba',
        tenantPhone: '+225 07 20 30 40 50',
        tenantEmail: 'nicolas.bamba@email.ci',
      },
      {
        id: 'unit-16',
        number: '2B',
        floor: 2,
        rooms: 3,
        size: 80,
        rent: 180000,
        status: 'Occupé',
        tenantId: 'tenant-12',
        tenantName: 'Julie Soro',
        tenantPhone: '+225 01 30 40 50 60',
        tenantEmail: 'julie.soro@email.ci',
      },
    ],
    description: 'Résidence moderne dans le centre-ville de Yamoussoukro, proche des services et commerces.',
    createdAt: '2024-01-05',
    updatedAt: '2024-01-15',
    photos: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
  },
  {
    id: 'prop-6',
    type: 'Immeuble',
    name: 'Résidence Yopougon',
    address: {
      street: 'Boulevard de la Paix',
      city: 'Abidjan',
      postalCode: '31 BP',
      country: 'Côte d\'Ivoire',
    },
    owner: {
      id: 'owner-6',
      name: 'Koffi Yao',
      email: 'koffi.yao@email.ci',
      phone: '+225 07 67 89 01 23',
    },
    status: 'Occupé',
    totalUnits: 16,
    occupiedUnits: 16,
    units: [],
    description: 'Résidence moderne dans le quartier populaire de Yopougon.',
    createdAt: '2024-01-12',
    updatedAt: '2024-01-18',
    photos: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
  },
]

/**
 * Récupère une propriété par son ID
 */
export function getPropertyById(id: string): Property | undefined {
  return mockProperties.find(p => p.id === id)
}

/**
 * Récupère les logements d'une propriété par son ID
 */
export function getUnitsByPropertyId(propertyId: string): Unit[] {
  const property = getPropertyById(propertyId)
  return property?.units || []
}


